import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import yfinance as yf
from io import BytesIO
import base64

# --- 1. CONFIGURATION & STYLING (Dark Brown Theme) ---
st.set_page_config(page_title="GT Valuation Terminal", page_icon="💼", layout="wide")

st.markdown("""
    <style>
    /* 1. Main Background - Dark Coffee Brown */
    .stApp { background-color: #2C241B; }
    
    /* 2. Sidebar Background - Darker Charcoal Brown */
    section[data-testid="stSidebar"] { background-color: #1E1915; }
    
    /* 3. Global Text - Gold/Beige/White */
    h1, h2, h3, h4 { color: #E6D5B8 !important; font-family: 'Helvetica Neue', sans-serif; }
    p, div, label, span { color: #F3F4F6; }
    
    /* 4. Sidebar Specifics */
    section[data-testid="stSidebar"] * { color: #D1C4E9 !important; }
    
    /* 5. Metric Cards */
    div[data-testid="stMetricValue"] { color: #FFD700; font-size: 28px; font-weight: 700; }
    div[data-testid="stMetricLabel"] { color: #E6D5B8; }
    
    /* 6. Buttons */
    .stButton>button {
        background-color: #8B4513; color: white !important;
        border: 1px solid #A0522D; border-radius: 6px;
    }
    .stButton>button:hover { background-color: #A0522D; }
    
    /* 7. Input Fields (Dark Mode friendly) */
    .stTextInput>div>div>input { color: black; }
    </style>
    """, unsafe_allow_html=True)

# --- 2. HELPER FUNCTIONS ---

def generate_template():
    """Generates a dummy Excel file."""
    data = {
        'Year': [2025, 2026, 2027, 2028, 2029],
        'Revenue': [1000, 1100, 1210, 1331, 1464],
        'EBITDA_Margin': [0.20, 0.22, 0.24, 0.25, 0.25],
        'D_and_A': [50, 55, 60, 65, 70],
        'CapEx': [60, 65, 70, 75, 80],
        'Change_in_NWC': [20, 22, 24, 26, 28]
    }
    df = pd.DataFrame(data)
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Model_Input')
    return output.getvalue()

@st.cache_data
def get_market_data(ticker):
    """Fetches live data from Yahoo Finance."""
    try:
        stock = yf.Ticker(ticker)
        info = stock.info
        # Get 10Y Treasury Yield as proxy for Risk Free Rate
        treasury = yf.Ticker("^TNX") 
        rf_rate = treasury.history(period="1d")['Close'].iloc[-1] / 100
        
        return {
            "beta": info.get('beta', 1.0),
            "price": info.get('currentPrice', 0),
            "mkt_cap": info.get('marketCap', 0),
            "debt": info.get('totalDebt', 0),
            "rf_rate": rf_rate,
            "name": info.get('longName', ticker)
        }
    except Exception as e:
        return None

def create_html_report(company_name, ev, wacc, upside, peers_data):
    """Generates a clean HTML Summary Report."""
    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; color: #333; }}
            .header {{ background-color: #2C241B; color: #FFD700; padding: 20px; text-align: center; }}
            .metric {{ font-size: 24px; font-weight: bold; color: #8B4513; }}
            table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #f2f2f2; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Valuation Tear Sheet: {company_name}</h1>
            <p>Generated by GT Valuation Engine</p>
        </div>
        <h2>1. Intrinsic Valuation (DCF)</h2>
        <p>Implied Enterprise Value: <span class="metric">${ev:,.0f}</span></p>
        <p>WACC Used: <span class="metric">{wacc:.2%}</span></p>
        <p>Upside Potential (95% Conf.): <span class="metric">${upside:,.0f}</span></p>
        
        <h2>2. Relative Valuation (Public Comps)</h2>
        {peers_data.to_html(index=False)}
        
        <br><hr>
        <p><i>Confidential - For Internal Use Only</i></p>
    </body>
    </html>
    """
    return html

# --- 3. SIDEBAR NAVIGATION ---
with st.sidebar:
    st.title("💼 GT Terminal")
    st.caption("Live Market Data Enabled v2.0")
    st.markdown("---")
    
    nav = st.radio("Module", 
        ["🗂️ Data & Scenarios", 
         "⚖️ Live WACC Builder", 
         "💎 Intrinsic Valuation", 
         "🌍 Relative Valuation",
         "⚡ Risk & Reporting"])
    
    st.markdown("---")
    st.info("💡 **Pro Tip:** Use 'Live WACC' to fetch real-time Beta.")

# --- 4. MAIN APP LOGIC ---

# --------------------------
# TAB 1: DATA & SCENARIOS
# --------------------------
if nav == "🗂️ Data & Scenarios":
    st.title("🗂️ Data Management")
    
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("1. Financial Model")
        uploaded_file = st.file_uploader("Upload Excel Model", type=['xlsx'])
        if uploaded_file:
            df = pd.read_excel(uploaded_file)
            st.session_state['data'] = df
            st.success("Data Loaded")
        else:
            st.warning("Awaiting Upload...")
            template = generate_template()
            st.download_button("💾 Get Template", data=template, file_name="GT_Template.xlsx")

    with col2:
        st.subheader("2. Scenario Manager")
        st.markdown("Save assumptions to toggle quickly.")
        
        if 'scenarios' not in st.session_state:
            st.session_state['scenarios'] = {}
        
        scen_name = st.text_input("Scenario Name (e.g., Bull Case)")
        if st.button("➕ Save Current State"):
            # Mock saving key variables (in real app, you'd link these to sliders)
            st.session_state['scenarios'][scen_name] = "Saved" 
            st.success(f"Scenario '{scen_name}' saved!")
        
        st.write("Saved Scenarios:", list(st.session_state['scenarios'].keys()))

# --------------------------
# TAB 2: LIVE WACC BUILDER
# --------------------------
elif nav == "⚖️ Live WACC Builder":
    st.title("⚖️ Live Cost of Capital")
    
    # LIVE TICKER SEARCH
    ticker = st.text_input("🔍 Search Ticker (e.g., AAPL, MSFT, RELIANCE.NS)", placeholder="Enter symbol to fetch data...")
    
    live_beta = 1.0
    live_rf = 0.04
    market_cap_display = "N/A"
    
    if ticker:
        with st.spinner(f"Connecting to Exchange for {ticker}..."):
            mkt_data = get_market_data(ticker)
            if mkt_data:
                live_beta = mkt_data['beta']
                live_rf = mkt_data['rf_rate']
                market_cap_display = f"${mkt_data['mkt_cap']/1e9:,.1f}B"
                st.success(f"✅ Connected: {mkt_data['name']} | Price: ${mkt_data['price']}")
            else:
                st.error("Ticker not found.")

    st.divider()
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.markdown("#### Equity (CAPM)")
        rf = st.number_input("Risk-Free Rate (%)", 0.0, 10.0, live_rf*100) / 100
        beta = st.number_input("Beta", 0.0, 5.0, live_beta)
        erp = st.number_input("Market Premium (%)", 0.0, 20.0, 6.0) / 100
        cost_equity = rf + beta * erp
        
    with col2:
        st.markdown("#### Debt & Tax")
        cost_debt = st.number_input("Pre-Tax Cost of Debt (%)", 0.0, 20.0, 6.5) / 100
        tax_rate = st.number_input("Tax Rate (%)", 0.0, 50.0, 25.0) / 100
        after_tax_debt = cost_debt * (1 - tax_rate)
        
    with col3:
        st.markdown("#### Capital Structure")
        st.metric("Market Cap (Live)", market_cap_display)
        equity_weight = st.slider("Equity Weight %", 0, 100, 80) / 100
        debt_weight = 1 - equity_weight
    
    wacc = (cost_equity * equity_weight) + (after_tax_debt * debt_weight)
    st.session_state['wacc'] = wacc # Save Global
    st.session_state['tax_rate'] = tax_rate
    st.session_state['ticker_name'] = ticker if ticker else "Project"

    st.metric("👉 Live WACC", f"{wacc:.2%}", delta="Updated Real-Time" if ticker else None)

# --------------------------
# TAB 3: INTRINSIC VALUATION (DCF)
# --------------------------
elif nav == "💎 Intrinsic Valuation":
    if 'data' not in st.session_state:
        st.warning("⚠️ Please upload data in the 'Data' tab.")
    else:
        st.title("💎 Discounted Cash Flow (DCF)")
        df = st.session_state['data'].copy()
        wacc = st.session_state.get('wacc', 0.10)
        tax = st.session_state.get('tax_rate', 0.25)
        
        tgr = st.slider("Terminal Growth Rate (%)", 1.0, 5.0, 2.5) / 100
        
        # Calculations
        df['EBITDA'] = df['Revenue'] * df['EBITDA_Margin']
        df['NOPAT'] = (df['EBITDA'] - df['D_and_A']) * (1 - tax)
        df['UFCF'] = df['NOPAT'] + df['D_and_A'] - df['CapEx'] - df['Change_in_NWC']
        
        # Discounting
        df['Period'] = range(1, len(df) + 1)
        df['PV'] = df['UFCF'] / ((1 + wacc) ** df['Period'])
        
        # Terminal Value
        tv = (df['UFCF'].iloc[-1] * (1 + tgr)) / (wacc - tgr)
        pv_tv = tv / ((1 + wacc) ** len(df))
        
        ev = df['PV'].sum() + pv_tv
        st.session_state['ev'] = ev # Save Global
        
        # Output
        k1, k2, k3 = st.columns(3)
        k1.metric("Enterprise Value", f"${ev:,.0f}")
        k2.metric("Term Value %", f"{(pv_tv/ev)*100:.1f}%")
        k3.metric("WACC", f"{wacc:.2%}")
        
        # Visuals
        fig = go.Figure(go.Waterfall(
            x = ["Explicit Cash Flows", "Terminal Value", "Total EV"],
            y = [df['PV'].sum(), pv_tv, ev],
            connector = {"line":{"color":"#E6D5B8"}},
        ))
        fig.update_layout(title="Valuation Bridge", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', font=dict(color="#E6D5B8"))
        st.plotly_chart(fig, use_container_width=True)

# --------------------------
# TAB 4: RELATIVE VALUATION (COMPS)
# --------------------------
elif nav == "🌍 Relative Valuation":
    st.title("🌍 Public Comparables Analysis")
    st.markdown("Compare your valuation against real-time market multiples.")
    
    comps_input = st.text_input("Enter Competitor Tickers (comma separated)", "GOOGL, MSFT, META")
    
    if st.button("🔄 Fetch Market Multiples"):
        tickers = [x.strip() for x in comps_input.split(',')]
        comp_data = []
        
        with st.spinner("Analyzing Peers..."):
            for t in tickers:
                try:
                    info = yf.Ticker(t).info
                    ev_comp = info.get('enterpriseValue', 0)
                    ebitda = info.get('ebitda', 0)
                    if ebitda > 0:
                        multiple = ev_comp / ebitda
                        comp_data.append({"Ticker": t, "EV/EBITDA": multiple, "Enterprise Value": ev_comp})
                except:
                    pass
        
        if comp_data:
            comp_df = pd.DataFrame(comp_data)
            st.session_state['comps'] = comp_df # Save for report
            
            # Display Average
            avg_mult = comp_df['EV/EBITDA'].mean()
            st.metric("Industry Average EV/EBITDA", f"{avg_mult:.1f}x")
            
            col1, col2 = st.columns([2, 1])
            with col1:
                st.dataframe(comp_df.style.format({"EV/EBITDA": "{:.1f}x", "Enterprise Value": "${:,.0f}"}), use_container_width=True)
            with col2:
                # Comparison Chart
                if 'ev' in st.session_state and 'data' in st.session_state:
                    my_ebitda = (st.session_state['data']['Revenue'][0] * st.session_state['data']['EBITDA_Margin'][0])
                    my_implied_mult = st.session_state['ev'] / my_ebitda
                    
                    fig = go.Figure(go.Bar(
                        x=['My Project', 'Industry Avg'],
                        y=[my_implied_mult, avg_mult],
                        marker_color=['#FFD700', '#8B4513']
                    ))
                    fig.update_layout(title="Multiple Benchmarking", paper_bgcolor='rgba(0,0,0,0)', font=dict(color="#E6D5B8"))
                    st.plotly_chart(fig, use_container_width=True)
        else:
            st.error("Could not fetch data. Check tickers.")

# --------------------------
# TAB 5: REPORTING
# --------------------------
elif nav == "⚡ Risk & Reporting":
    if 'ev' not in st.session_state:
        st.warning("⚠️ Run Valuation first.")
    else:
        st.title("⚡ Risk Analysis & Reporting")
        
        # 1. RISK SIMULATION
        st.subheader("Monte Carlo Simulation")
        vol = st.slider("Volatility", 5, 50, 20) / 100
        base_ev = st.session_state['ev']
        sims = base_ev * (1 + np.random.normal(0, vol, 1000))
        upside = np.percentile(sims, 95)
        
        fig = px.histogram(sims, nbins=50, title="Valuation Distribution", color_discrete_sequence=['#FFD700'])
        fig.update_layout(paper_bgcolor='rgba(0,0,0,0)', font=dict(color="#E6D5B8"))
        st.plotly_chart(fig, use_container_width=True)
        
        st.divider()
        
        # 2. REPORT GENERATION
        st.subheader("📄 Generate Client Report")
        if st.button("🖨️ Create One-Pager"):
            # Prepare Data
            ticker_name = st.session_state.get('ticker_name', 'Project Alpha')
            wacc_used = st.session_state.get('wacc', 0)
            comps_df = st.session_state.get('comps', pd.DataFrame())
            
            # Generate HTML
            html_report = create_html_report(ticker_name, base_ev, wacc_used, upside, comps_df)
            
            # Convert to Base64 for Download
            b64 = base64.b64encode(html_report.encode()).decode()
            href = f'<a href="data:text/html;base64,{b64}" download="Valuation_Report.html" style="background-color: #FFD700; color: black; padding: 10px; text-decoration: none; border-radius: 5px; font-weight: bold;">📥 Download PDF/HTML Report</a>'
            st.markdown(href, unsafe_allow_html=True)
            st.success("Report Generated! Click button above.")
